#line 2 "2205014.cpp"

#line 4 "2205014.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[257] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   63,   61,    1,   60,    9,   36,
       61,    5,   58,   29,   10,   11,    5,    4,   16,    4,
       61,    5,   19,   19,   17,    6,    7,    6,   21,   21,
       14,   15,   58,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   12,   58,   13,   35,
       33,   30,   35,   43,   40,   37,   43,   47,   46,   45,
       52,   51,   52,   52,   25,   24,   62,   62,   62,    1,
        6,    0,    0,   59,    8,    0,   57,    0,    3,   53,
       20,   48,   44,    0,   19,   19,   55,   55,   55,   55,

       58,   58,   21,    0,   21,   21,   21,   21,   21,    2,
       21,   21,   21,   21,    2,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   34,   32,   34,   38,   42,   42,
        0,   49,   50,    0,    0,    0,    0,    0,    0,   53,
       53,    0,   55,   55,   55,    0,    0,   20,    0,   18,
       19,    0,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,    0,
       39,    0,   28,    0,    0,    0,    0,   56,    0,   53,
        0,   53,    0,   20,   20,   20,   54,   55,   55,   20,
       55,    0,   55,   55,    0,    0,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   31,   41,    0,
        0,    0,   20,   55,   55,   55,   55,   20,    0,   20,
       20,    0,   22,   21,   21,   21,   21,   21,   21,   21,
        0,    0,    0,   55,   20,    0,    0,   20,   55,   20,
       21,   21,   21,    0,   23,    0,   20,    0,   21,   21,
        0,   26,    0,    0,   27,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   26,   28,   26,
       29,   30,   31,   29,   29,   29,   29,   29,   29,   32,
       29,   33,   34,   35,   29,   29,   36,   37,   29,   29,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   29,   52,   53,   29,   54,
       55,   56,   29,   57,   58,   59,   60,   61,   62,   63,
       29,   29,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    4,
        1,    1,    1,    5,    4,    4,    4,    4,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1,    6,    4,    4,    4,    4,    4,    4,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[274] =
    {   0,
        0,    0,   65,   66,   67,   68,   73,   74,   75,   76,
      650,  649,   58,   59,  651,  654,  644,  654,  620,  654,
       38,  613,   74,   76,  654,  654,  610,   73,  654,   68,
       82,   91,  100,  105,  654,   87,  604,  103,    0,  619,
      654,  654,  654,  564,   79,   83,  562,   86,  557,   63,
      554,  555,   81,  509,  507,  511,  654,  495,  654,  654,
      654,  654,  159,  654,  654,  654,  220,  654,  654,  654,
      654,  654,  541,  545,  654,  654,  654,    0,  526,  553,
      654,  507,  499,  654,  654,  513,  512,  279,  654,  130,
      137,  654,  654,  151,  162,  167,    0,  181,  325,  141,

      527,  526,    0,  538,  500,  481,  486,  474,  478,  457,
      458,  454,  446,  439,    0,  438,  439,  429,  427,  438,
      428,  420,  421,  413,  654,  654,  208,  654,  456,  654,
      227,  654,  654,  433,  415,  395,  397,  123,  369,  156,
      221,  247,  274,  173,    0,  192,  212,  282,    0,  391,
      287,  421,  386,  380,  368,  363,  372,  365,  360,  361,
      348,  350,  337,  336,  327,  325,  316,  320,  308,  337,
      654,  363,  654,  319,  298,  289,  127,  180,  426,  292,
      224,  253,  312,  376,  382,  418,  328,    0,  340,  253,
      323,  357,  401,  421,  326,  140,  283,  283,  266,  272,

      262,  262,  258,  265,  269,  264,  257,  654,  654,  271,
      242,  231,  429,  432,  443,  435,  448,  457,  471,  192,
      476,  482,  275,  228,  227,  231,  222,  216,  208,  203,
      187,  170,  169,  487,  492,  495,  501,  504,  512,  517,
      154,  147,  158,  156,  654,  126,  522,  525,  107,  106,
      119,  654,  108,   71,  654,  654,  564,  570,  576,  582,
      588,  594,  600,  604,  607,  613,  619,  625,  628,  634,
      638,   86,  644
    } ;

static const flex_int16_t yy_def[274] =
    {   0,
      256,    1,  257,  257,  258,  258,  259,  259,  260,  260,
      261,  261,  262,  262,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  263,  256,  256,  256,  256,  256,  256,
      256,  256,  264,  264,  256,  256,  256,  256,  265,  265,
      256,  256,  256,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  256,  256,  256,  256,
      256,  256,  266,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  267,  256,  256,
      256,  256,  256,  256,  256,  268,  268,  256,  256,  256,
      264,  256,  256,  256,  264,  264,  269,  269,  269,  269,

      256,  256,  265,  256,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  267,  256,  256,  256,  270,  256,  256,
      256,  256,  269,  269,  269,  256,  256,  271,  272,   99,
      271,  273,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  256,
      256,  256,  256,  256,  256,  256,  270,  270,  256,  256,
      256,  256,  256,  271,  271,  264,  256,  269,  269,  272,
       99,  256,  269,  269,  273,  273,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  256,  256,  256,
      256,  256,  264,  269,  269,  269,  269,  271,  256,  272,
      264,  256,  273,  265,  265,  265,  265,  265,  265,  265,
      256,  256,  256,  269,  271,  256,  256,  256,  269,  264,
      265,  265,  265,  256,  256,  256,  264,  256,  265,  265,
      256,  256,  256,  256,  256,    0,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256
    } ;

static const flex_int16_t yy_nxt[722] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   34,
       35,   36,   37,   38,   39,   39,   39,   39,   39,   39,
       39,   39,   40,   39,   39,   39,   39,   41,   16,   42,
       43,   39,   39,   44,   45,   46,   47,   48,   49,   39,
       50,   39,   51,   39,   39,   39,   52,   53,   39,   54,
       55,   56,   39,   57,   58,   59,   43,   61,   61,   65,
       65,   66,   66,   62,   62,   69,   69,   72,   72,   78,
       78,   85,   89,   82,   87,   89,   73,   73,   83,  190,
       84,   74,   74,   79,   79,   84,   84,   90,  255,   91,

       91,   91,   92,   63,   63,   67,   67,   93,  101,   81,
      115,   70,   70,   84,   88,   94,  116,   95,   95,   96,
       94,  106,   96,   96,   96,   81,  102,   98,  107,  109,
      119,  178,   98,  108,  254,  178,   99,  110,  112,  120,
      113,  100,  121,  253,  223,  140,  100,  141,  141,  141,
      196,  115,   90,  115,   91,   91,   91,  142,  151,  151,
      151,  179,   99,  126,  143,  179,   90,  126,   91,   91,
       91,  140,  252,  180,  180,  180,  126,   94,  144,   95,
       95,   96,   94,  142,   96,   96,   96,  251,  178,   98,
      185,  185,  185,  146,   98,  146,  147,  126,  148,  148,

      148,  126,  126,  100,  250,  115,  126,  147,  100,  186,
      186,  186,  126,  249,  246,  126,  245,  126,  179,  126,
      244,  127,  128,  219,  129,  170,  170,  170,  130,  187,
      187,  187,  170,  170,  170,  170,  140,  130,  141,  141,
      141,  182,  182,  182,  172,  172,  172,  219,  142,  170,
      170,  172,  172,  172,  172,  170,  243,  115,  130,  181,
      115,  181,  130,  130,  182,  182,  182,  130,  172,  172,
      182,  182,  182,  130,  172,  115,  130,  115,  130,  242,
      130,  241,  131,   86,  219,  196,  183,   86,  183,  147,
      233,  184,  184,  184,  220,  232,   86,  147,  231,  148,

      148,  148,  192,  115,  151,  151,  151,  140,  219,  180,
      180,  180,  230,  229,  193,  228,  115,   86,  227,  142,
      115,   86,   86,  189,  226,  225,   86,  147,  194,  213,
      213,  213,   86,  224,  115,   86,  196,   86,  256,   86,
      149,  212,  150,  150,  150,  187,  187,  187,  211,  150,
      150,  150,  150,  210,  208,  208,  208,  218,  218,  218,
      207,  208,  208,  208,  208,  115,  206,  150,  150,  150,
      150,  150,  150,  138,  221,  221,  221,  138,  208,  208,
      209,  209,  209,  205,  208,  204,  138,  209,  209,  209,
      209,  147,  203,  184,  184,  184,  202,  256,  115,  185,

      185,  185,  115,  201,  209,  209,  115,  138,  200,  215,
      209,  138,  138,  222,  199,  222,  138,  214,  218,  218,
      218,  198,  138,  216,  115,  138,  115,  138,  197,  138,
      177,  196,  191,  147,  177,  186,  186,  186,  151,  151,
      151,  176,  175,  177,  147,  174,  213,  213,  213,  235,
      235,  235,  185,  185,  185,  236,  173,  236,  171,  217,
      235,  235,  235,  169,  177,  218,  218,  218,  177,  177,
      234,  168,  256,  177,  218,  218,  218,  167,  166,  177,
      165,  164,  177,  237,  177,  237,  177,  163,  238,  238,
      238,  256,  162,  221,  221,  221,  115,  161,  189,  240,

      240,  240,  115,  239,  235,  235,  235,  256,  160,  235,
      235,  235,  247,  247,  247,  159,  158,  144,  238,  238,
      238,  238,  238,  238,  236,  157,  236,  156,  155,  235,
      235,  235,  256,  214,  240,  240,  240,  256,  154,  247,
      247,  247,  238,  238,  238,  248,  153,  152,   84,   84,
      139,  139,  137,  136,   80,  135,  133,  132,  217,   85,
      124,  123,  122,  234,   60,   60,   60,   60,   60,   60,
       64,   64,   64,   64,   64,   64,   68,   68,   68,   68,
       68,   68,   71,   71,   71,   71,   71,   71,   75,   75,
       75,   75,   75,   75,   77,   77,   77,   77,   77,   77,

       86,  118,   86,   86,   86,   86,   97,   97,  117,   97,
      103,  114,  103,  125,  111,  125,  125,  125,  125,  134,
      105,  134,  134,  104,  134,  138,   81,  138,  138,  138,
      138,  145,   84,  145,  177,   84,  177,  177,  177,  177,
      188,  188,   81,  188,  195,   80,  195,  195,  195,  195,
      256,   76,   76,   15,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256
    } ;

static const flex_int16_t yy_chk[722] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    5,    6,    3,    4,    7,    8,    9,   10,   13,
       14,   23,   30,   21,   24,   28,    9,   10,   21,  272,
       30,    9,   10,   13,   14,   28,   23,   31,  254,   31,

       31,   31,   32,    3,    4,    5,    6,   32,   36,   36,
       50,    7,    8,   32,   24,   33,   50,   33,   33,   33,
       34,   45,   34,   34,   34,   38,   38,   33,   45,   46,
       53,  138,   34,   45,  253,  177,   33,   46,   48,   53,
       48,   33,   53,  251,  196,   90,   34,   90,   90,   90,
      196,  250,   91,  249,   91,   91,   91,   90,  100,  100,
      100,  138,   33,   63,   91,  177,   94,   63,   94,   94,
       94,  140,  246,  140,  140,  140,   63,   95,   91,   95,
       95,   95,   96,  140,   96,   96,   96,  244,  178,   95,
      144,  144,  144,   98,   96,   98,   98,   63,   98,   98,

       98,   63,   63,   95,  243,  242,   63,  146,   96,  146,
      146,  146,   63,  241,  233,   63,  232,   63,  178,   63,
      231,   63,   67,  220,   67,  127,  127,  127,   67,  147,
      147,  147,  127,  127,  127,  127,  141,   67,  141,  141,
      141,  181,  181,  181,  131,  131,  131,  220,  141,  127,
      127,  131,  131,  131,  131,  127,  230,  229,   67,  142,
      228,  142,   67,   67,  142,  142,  142,   67,  131,  131,
      182,  182,  182,   67,  131,  227,   67,  226,   67,  225,
       67,  224,   67,   88,  190,  223,  143,   88,  143,  143,
      212,  143,  143,  143,  190,  211,   88,  148,  210,  148,

      148,  148,  151,  207,  151,  151,  151,  180,  190,  180,
      180,  180,  206,  205,  151,  204,  203,   88,  202,  180,
      201,   88,   88,  148,  200,  199,   88,  183,  151,  183,
      183,  183,   88,  198,  197,   88,  195,   88,  191,   88,
       99,  176,   99,   99,   99,  187,  187,  187,  175,   99,
       99,   99,   99,  174,  170,  170,  170,  189,  189,  189,
      169,  170,  170,  170,  170,  168,  167,   99,   99,   99,
       99,   99,   99,  139,  192,  192,  192,  139,  170,  170,
      172,  172,  172,  166,  170,  165,  139,  172,  172,  172,
      172,  184,  164,  184,  184,  184,  163,  185,  162,  185,

      185,  185,  161,  160,  172,  172,  159,  139,  158,  185,
      172,  139,  139,  193,  157,  193,  139,  184,  193,  193,
      193,  156,  139,  185,  155,  139,  154,  139,  153,  139,
      179,  152,  150,  186,  179,  186,  186,  186,  194,  194,
      194,  137,  136,  179,  213,  135,  213,  213,  213,  214,
      214,  214,  216,  216,  216,  215,  134,  215,  129,  186,
      215,  215,  215,  124,  179,  217,  217,  217,  179,  179,
      213,  123,  218,  179,  218,  218,  218,  122,  121,  179,
      120,  119,  179,  219,  179,  219,  179,  118,  219,  219,
      219,  221,  117,  221,  221,  221,  116,  114,  218,  222,

      222,  222,  113,  221,  234,  234,  234,  235,  112,  235,
      235,  235,  236,  236,  236,  111,  110,  221,  237,  237,
      237,  238,  238,  238,  239,  109,  239,  108,  107,  239,
      239,  239,  240,  235,  240,  240,  240,  247,  106,  247,
      247,  247,  248,  248,  248,  238,  105,  104,  102,  101,
       87,   86,   83,   82,   80,   79,   74,   73,  240,   58,
       56,   55,   54,  247,  257,  257,  257,  257,  257,  257,
      258,  258,  258,  258,  258,  258,  259,  259,  259,  259,
      259,  259,  260,  260,  260,  260,  260,  260,  261,  261,
      261,  261,  261,  261,  262,  262,  262,  262,  262,  262,

      263,   52,  263,  263,  263,  263,  264,  264,   51,  264,
      265,   49,  265,  266,   47,  266,  266,  266,  266,  267,
       44,  267,  267,   40,  267,  268,   37,  268,  268,  268,
      268,  269,   27,  269,  270,   22,  270,  270,  270,  270,
      271,  271,   19,  271,  273,   17,  273,  273,  273,  273,
       15,   12,   11,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2205014.l"






#line 11 "2205014.l"
#include "temp.cpp"

#line 703 "2205014.cpp"
#line 704 "2205014.cpp"

#define INITIAL 0
#define CONST_CHAR_TOKENIZER 1
#define STRING_TOKENIZER 2
#define SINGLE_LINE_COMMENT_TOKENIZER 3
#define MULTI_LINE_COMMENT_TOKENIZER 4
#define DEFINE_TOKENIZER 5
#define INCLUDE_TOKENIZER 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 96 "2205014.l"

#line 929 "2205014.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 257 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 654 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 97 "2205014.l"
{} 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "2205014.l"
{handleFileWriting(generateKEYWORDToken(yytext));}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 101 "2205014.l"
{handleFileWriting(new TokenDetails("INCOP", yytext));}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 103 "2205014.l"
{handleFileWriting(new TokenDetails("ADDOP", yytext));}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 105 "2205014.l"
{handleFileWriting(new TokenDetails("MULOP", yytext));}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 107 "2205014.l"
{handleFileWriting(new TokenDetails("RELOP", yytext));}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "2205014.l"
{handleFileWriting(new TokenDetails("ASSIGNOP", yytext));}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 111 "2205014.l"
{handleFileWriting(new TokenDetails("LOGICOP", yytext));}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 113 "2205014.l"
{handleFileWriting(new TokenDetails("NOT", yytext));}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 115 "2205014.l"
{countParen++; handleFileWriting(new TokenDetails("LPAREN", yytext));}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 117 "2205014.l"
{
    cout<<countParen;
    countParen--;
    if(countParen<0)
    {handleErrorLogging("Unmatched closing parenthesis or Unmatched closing brace", yytext, 1);
    countParen=0;
    }
    else
    handleFileWriting(new TokenDetails("RPAREN", yytext));
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 128 "2205014.l"
{countCurly++; handleFileWriting(generateLCURLToken());}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 130 "2205014.l"
{
    countCurly--;
    if(countCurly<0)
    {handleErrorLogging("Unmatched closing parenthesis or Unmatched closing brace", yytext, 1);
    countCurly=0;
    }
    else
    handleFileWriting(generateRCURLToken());
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 140 "2205014.l"
{handleFileWriting(new TokenDetails("LTHIRD", yytext));}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 142 "2205014.l"
{handleFileWriting(new TokenDetails("RTHIRD", yytext));}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "2205014.l"
{handleFileWriting(new TokenDetails("COMMA", yytext));}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 146 "2205014.l"
{handleFileWriting(new TokenDetails("SEMICOLON", yytext));}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 148 "2205014.l"
{handleFileWriting(generateHEXADECIMALToken(yytext));}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 150 "2205014.l"
{handleFileWriting(generateIDCONSTToken("CONST_INT",yytext));}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 152 "2205014.l"
{handleFileWriting(generateIDCONSTToken("CONST_FLOAT",yytext));}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 154 "2205014.l"
{
    if(strlen(yytext)>31)
    {
        handleErrorLogging("Identifier length exceed!", yytext, 1);
    }
    else
    handleFileWriting(generateIDCONSTToken("ID",yytext));
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 163 "2205014.l"
{
    string str=yytext;
    handleFileWriting(new TokenDetails("STRING", str.substr(3, str.size()-5)));
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 168 "2205014.l"
{
    curr_scanned_str="";
    BEGIN DEFINE_TOKENIZER;
}
	YY_BREAK

case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 174 "2205014.l"
{ handleFileWriting(new TokenDetails("DEFINE", curr_scanned_str));
lineCount++;
BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(DEFINE_TOKENIZER):
#line 178 "2205014.l"
{handleFileWriting(new TokenDetails("DEFINE", curr_scanned_str));
BEGIN INITIAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 180 "2205014.l"
{curr_scanned_str+=yytext;}
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 183 "2205014.l"
{
    BEGIN INCLUDE_TOKENIZER;
}
	YY_BREAK


case 27:
YY_RULE_SETUP
#line 188 "2205014.l"
{}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 189 "2205014.l"
{
    handleFileWriting(generateINCLUDEToken(yytext));
    BEGIN INITIAL;    
}
	YY_BREAK

case 29:
YY_RULE_SETUP
#line 195 "2205014.l"
{
curr_char_str="";
BEGIN CONST_CHAR_TOKENIZER;
}
	YY_BREAK

case 30:
YY_RULE_SETUP
#line 202 "2205014.l"
{
if(validEscape==true)
handleFileWriting(generateCONST_CHARToken());
else
handleErrorLogging("Invalid escape character", "\'"+curr_char_str+"\'",2);
validEscape=true;
BEGIN INITIAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 210 "2205014.l"
{
    curr_char_str+=yytext;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 214 "2205014.l"
{
    curr_char_str+=yytext;
}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 218 "2205014.l"
{
    handleErrorLogging(errMsg5, "\'"+curr_char_str, 2);
    lineCount++;
    BEGIN INITIAL;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 224 "2205014.l"
{
    curr_char_str+=yytext;
    validEscape=false;
}
	YY_BREAK
case YY_STATE_EOF(CONST_CHAR_TOKENIZER):
#line 229 "2205014.l"
{
    handleErrorLogging(errMsg5, "\'"+curr_char_str, 2);
    BEGIN INITIAL;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 234 "2205014.l"
{curr_char_str+=yytext;}
	YY_BREAK

case 36:
YY_RULE_SETUP
#line 237 "2205014.l"
{
    tokenLineCount=1;
    curr_scanned_str="\"";
    curr_replaced_str="";
    BEGIN STRING_TOKENIZER;
}
	YY_BREAK

case 37:
YY_RULE_SETUP
#line 246 "2205014.l"
{
    curr_scanned_str+=yytext;
    tokenLineCount=0;
    handleFileWriting(generateSTRINGToken());
    BEGIN INITIAL;
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 253 "2205014.l"
{
    tokenLineCount++;
    curr_scanned_str+=yytext;
    lineCount++;
}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 259 "2205014.l"
{
    curr_scanned_str+="\\\"";
    handleErrorLogging(errMsg9, curr_scanned_str, 1);
    lineCount++;
    tokenLineCount=0;
    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(STRING_TOKENIZER):
#line 267 "2205014.l"
{
    handleErrorLogging(errMsg9, curr_scanned_str, 1);
    tokenLineCount=0;
    BEGIN INITIAL;
}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 273 "2205014.l"
{
    handleErrorLogging(errMsg9, curr_scanned_str, 1);
    lineCount++;
    tokenLineCount=0;
    BEGIN INITIAL;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 280 "2205014.l"
{
    curr_scanned_str+=yytext;
    curr_replaced_str+=getActualCharacter(yytext);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 285 "2205014.l"
{curr_scanned_str+=yytext;
    curr_replaced_str+= getActualCharacter(yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 290 "2205014.l"
{curr_scanned_str+=yytext; curr_replaced_str+=yytext;}
	YY_BREAK

case 44:
YY_RULE_SETUP
#line 293 "2205014.l"
{
    back_slash_encounter=false;
    curr_scanned_str="//";
    BEGIN SINGLE_LINE_COMMENT_TOKENIZER;
} 
	YY_BREAK

case 45:
YY_RULE_SETUP
#line 301 "2205014.l"
{back_slash_encounter=true;curr_scanned_str+=yytext;}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 303 "2205014.l"
{
    if(back_slash_encounter)
    {
        curr_scanned_str+=yytext;
        lineCount++;
        back_slash_encounter=false;
    }
    else{
        handleFileWriting(new TokenDetails("COMMENT", curr_scanned_str));
        lineCount++;
        BEGIN INITIAL;
    }
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 316 "2205014.l"
{curr_scanned_str+=yytext; back_slash_encounter=false;}
	YY_BREAK
case YY_STATE_EOF(SINGLE_LINE_COMMENT_TOKENIZER):
#line 318 "2205014.l"
{handleFileWriting(new TokenDetails("COMMENT", curr_scanned_str));
BEGIN INITIAL;}
	YY_BREAK

case 48:
YY_RULE_SETUP
#line 322 "2205014.l"
{
    tokenLineCount=1;
    curr_scanned_str="/*";
    commentNest=0;
    BEGIN MULTI_LINE_COMMENT_TOKENIZER;
}
	YY_BREAK

case 49:
YY_RULE_SETUP
#line 331 "2205014.l"
{ curr_scanned_str+=yytext; if(commentNest==0){ 
handleFileWriting(new TokenDetails("COMMENT", curr_scanned_str));
tokenLineCount=0;
BEGIN INITIAL;}
else{
    commentNest--;
}
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 340 "2205014.l"
{curr_scanned_str+=yytext; commentNest++;}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 342 "2205014.l"
{
    tokenLineCount++;
    curr_scanned_str+="\n";
    lineCount++;
}
	YY_BREAK
case YY_STATE_EOF(MULTI_LINE_COMMENT_TOKENIZER):
#line 348 "2205014.l"
{
    handleErrorLogging(errMsg8, curr_scanned_str, 1);
    tokenLineCount=0;
    BEGIN INITIAL;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 354 "2205014.l"
{curr_scanned_str+=yytext;}
	YY_BREAK

case 53:
YY_RULE_SETUP
#line 358 "2205014.l"
{handleErrorLogging(errMsg1, yytext, 2);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 360 "2205014.l"
{handleErrorLogging(errMsg2, yytext, 2);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 362 "2205014.l"
{handleErrorLogging(errMsg3, yytext, 1);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 364 "2205014.l"
{handleErrorLogging(errMsg4, yytext, 2);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 366 "2205014.l"
{handleErrorLogging(errMsg6, yytext, 2);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 368 "2205014.l"
{handleFileWriting(new TokenDetails("BITOP", yytext));}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 370 "2205014.l"
{handleFileWriting(new TokenDetails("COMPOUND_ASSIGN", yytext));}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 372 "2205014.l"
{lineCount++;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 374 "2205014.l"
{handleErrorLogging(errMsg7, yytext, 1);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 376 "2205014.l"
ECHO;
	YY_BREAK
#line 1470 "2205014.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INCLUDE_TOKENIZER):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 257 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 257 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 256);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 376 "2205014.l"


int main(int argc, char *argv[])
{

    if (argc < 2)
    {
        cout << "Please provide the name of the input file as argument\n";
        return 0;
    }

    FILE *fin;

    fin = fopen(argv[1], "r");

    if (fin == NULL)
    {
        cout << "The input file cannot be opened.\n";
        return -1;
    }

    symbolTable=new SymbolTable(7);
    symbolTable->enterScope(); // root scope
    yyin = fin;
    yylex();

    // printing all scope tables after lexical analysis is complete
    symbolTable->printAllScopes2(logofs);
    logofs<<endl;

    // printing line, error and warning counts
    logofs << "Total lines: " << lineCount << endl;
    logofs << "Total errors: " << errorCount << endl;
    // logout << "Total warnings: " << warning_count << endl;

    fclose(yyin);
    tokenofs.close();
    logofs.close();

    return 0;
}
